// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.

export const environment = {
  production: false,
  api_url: 'https://ikkaapoker.czargaming.com/api/',
  login_api: 'affiliateAccount/login',
  siteid: '',
  registration_api: 'affiliateAccount/register',
  validatesession_api: 'agentAccount/getProfile',
  getprofile_api: 'affiliateAccount/getProfile',
  updateprofile_api: 'affiliateAccount/updateProfile',
  forgotpassword_api: 'affiliateAccount/forgotPassword',
  resetpassword_api: 'player/resetPassword',
  gethistory_api: 'history/transaction',
  getgamehistory_api: 'history/game',
  logout_api: 'agentAccount/logout',
  verifyaccount_api: 'player/verifyAccount',
  getbalance_api: 'cashier/balance',
  getNetworkbalance_api: "agentCashier/balanceSummary",
  withdraw_api: 'cashier/withdraw',
  deposit_api: 'agentCashier/deposit',
  getopen_withdraw_request_api: 'cashier/getOpenWithdrawRequests',
  cancelwithdrawrequest_api: 'cashier/cancelWithdrawRequest',
  getlblist_api: 'leaderboard/list',
  getlbparticipants_api: 'leaderboard/getParticipants',
  getcountries_api: 'player/getCountries',
  resetplaymoney_balance_api: 'cashier/resetPlayMoneyBalance',
  getpayment_systems_api: 'cashier/getPaymentSystems',
  cp_exchange_rates_api: 'cp/exchangeRates',
  cp_player_levels_api: 'cp/playerLevels',
  cp_exchange_api: 'cp/exchange',
  default_currency: 'INR',
  default_gateway: 'CASHFREE',
  cp_currency: 'COMPPOINTS',
  menu_options: [
    { name: 'menu.aboutus', link: '/aboutus' },
    { name: 'menu.tournaments', link: '/tournaments' },
    { name: 'menu.promotions', link: '/promotions' }
  ],
  menu_postlogin_options: [
    { name: 'menu.aboutus', link: '/aboutus' },
    { name: 'menu.tournaments', link: '/tournaments' },
    { name: 'menu.promotions', link: '/promotions' },
    { name: 'menu.deposit', link: '/cashier/deposit' },
    { name: 'menu.withdraw', link: '/cashier/withdraw' },
    { name: 'menu.history', link: '/history' },
    { name: 'menu.game', link: '/history/game' },
    { name: 'menu.cpexchange', link: '/cashier/cpExchange' },
    { name: 'menu.reversewithdraw', link: '/cashier/reverseWithdraw' },
  ],
  create_player_api: "agentAccount/createPlayer",
  get_playerslist_api: "agentAccount/getPlayersList",
  transaction_api: "agentHistory/transactions",
  get_agentlist_api: "agentAccount/getAgentsList",
  get_captcha: "player/generateCaptcha",
  get_countries: "agentAccount/getCountries",
  get_referralCodes: "affiliateCashier/referralCodes",
  get_refTree: "agentHistory/referringTree",
  get_revenue_from_users: "agentHistory/revenuFromUsers",
  get_link_codes: "affiliateCashier/linkCodes",
  baseUrl: "https://ikkaapoker.czargaming.com",
  resetPasswordForSubUser: "agentAccount/resetPasswordForSubUser",
  transfer_amount: "agentCashier/transfer",
  add_bankaccount: "agentCashier/addBankAccount",
  unlockLockForSubUser: "agentAccount/updateStatusForSubUser",
  get_bankaccounts: "agentCashier/getBankAccounts",
  delete_bankaccounts: "agentCashier/deleteBankAccounts",
  get_campaigncodes: "agentCashier/getCampaignCodes",
  verifyaccount: "agentAccount/verifyPlayer",
  withdraw: "agentCashier/withdraw",
  campaignList: "affiliateCashier/campaignsList",
  addCampaign: "affiliateCashier/addCampaign",
  editCampaign: "affiliateCashier/editCampaign",
  updatepassword_api: 'affiliateAccount/updatePassword',
  statisticsSummary: "affiliateHistory/getStatisticsSummary",
  payments: "affiliateHistory/getStatisticsPaymentHistory",
  chargebacks: "affiliateHistory/getStatisticsChargebacks",
  cancledpayments: "affiliateHistory/getStatisticsCancelledPayments",
  rvnadjustments: "affiliateHistory/getStatisticsRevenueAdjustments",
  campaignstats: "affiliateHistory/getStatisticsCampaign"

};

